import React, { useState } from 'react';
import { generateVisualMetaphor } from '../services/gemini';

export const ImageGenerationView: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [size, setSize] = useState<"1K" | "2K" | "4K">("1K");

  const handleGenerate = async () => {
    if (!prompt) return;
    setLoading(true);
    setGeneratedImage(null);
    try {
      const imageBase64 = await generateVisualMetaphor(prompt, size);
      setGeneratedImage(imageBase64);
    } catch (e) {
      console.error(e);
      alert("Failed to generate image. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center p-8 h-full bg-slate-50 overflow-y-auto" role="region" aria-label="Visual Metaphor Generator">
      <div className="w-full max-w-2xl bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
        <h2 className="text-2xl font-bold text-slate-800 mb-2">Visual Metaphors</h2>
        <p className="text-slate-500 mb-6">Sometimes feelings are easier to understand as abstract art. Describe an emotion or situation to visualize it.</p>
        
        <div className="space-y-4">
          <div className="flex flex-col space-y-2">
            <label htmlFor="emotion-prompt" className="text-sm font-medium text-slate-700">Emotion or Concept</label>
            <input 
              id="emotion-prompt"
              type="text" 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., Overwhelmed by loud noises in a crowd"
              className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div className="flex flex-col space-y-2">
             <span className="text-sm font-medium text-slate-700" id="size-label">Image Quality</span>
             <div className="flex space-x-2" role="group" aria-labelledby="size-label">
               {(["1K", "2K", "4K"] as const).map((s) => (
                 <button
                   key={s}
                   onClick={() => setSize(s)}
                   aria-pressed={size === s}
                   className={`px-4 py-2 rounded-md text-sm font-medium border focus:outline-none focus:ring-2 focus:ring-purple-500 ${size === s ? 'bg-purple-100 border-purple-500 text-purple-700' : 'bg-white border-slate-300 text-slate-600 hover:bg-slate-50'}`}
                 >
                   {s}
                 </button>
               ))}
             </div>
          </div>

          <button 
            onClick={handleGenerate}
            disabled={loading || !prompt}
            className={`w-full py-3 rounded-lg font-bold text-white transition-all focus:outline-none focus:ring-2 focus:ring-purple-500 ${loading ? 'bg-slate-400' : 'bg-purple-600 hover:bg-purple-700'}`}
          >
            {loading ? 'Generating Art...' : 'Visualize Emotion'}
          </button>
        </div>
      </div>

      {generatedImage && (
        <div className="mt-8 animate-fade-in w-full max-w-2xl">
          <div className="bg-white p-4 rounded-xl shadow-lg border border-slate-100">
            <img src={generatedImage} alt={`Visual metaphor for: ${prompt}`} className="w-full h-auto rounded-lg" />
            <div className="mt-4 flex justify-between items-center">
              <span className="text-xs text-slate-400">Generated by Gemini 3 Pro Image Preview</span>
              <a 
                href={generatedImage} 
                download="emotion-metaphor.png"
                className="text-purple-600 text-sm font-medium hover:underline focus:outline-none focus:ring-2 focus:ring-purple-500 rounded p-1"
                aria-label="Download generated image"
              >
                Download Image
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
